workflows:
  android-workflow:
    name: Grok Chaos Apex – Instant APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: "17"
        ANDROID_SDK_ROOT: "/Users/builder/exported/android-sdk"
    scripts:
      - name: Set up JDK 17
        script: echo "y" | $SDKMANAGER "platform-tools" "platforms;android-34" "build-tools;34.0.0" > /dev/null
      - name: Build Debug APK (no wrapper needed)
        script: |
          # Use the globally installed Gradle that ships with Codemagic
          gradle assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - wolfelindsey1104@gmail.com # ← PUT YOUR REAL EMAIL HERE
        notify:
          success: true
