workflows:
  android-chaos-apex:
    name: Build Grok Chaos Apex APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      java_version: 17  # Pin to JDK 17 for stability
    scripts:
      # Pre-build: Just make executable, no clean (avoids JVM trigger)
      - name: Pre-build Setup
        script: chmod +x gradlew
      # Build the debug APK
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # Update with your email
