workflows:
  android-workflow:
    name: Grok Chaos Apex – Build APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        - android_signing   # ← you can ignore this for now (debug build doesn’t need it)
      vars:
        JAVA_VERSION: "17"   # ← correct way to set Java version on Codemagic
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Make gradlew executable
        script: |
          chmod +x ./gradlew
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - YOUR-EMAIL-HERE@example.com   # ← change to your real email
        notify:
          success: true
          failure: true
