workflows:
  android-debug:
    name: Grok Chaos Apex – Instant Debug APK
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Build APK (Codemagic’s built-in Gradle)
        script: |
          gradle assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - PUT-YOUR-REAL-EMAIL-HERE@example.com
        notify:
          success: true
          failure: false
