workflows:
  android-chaos-apex:
    name: Build Grok Chaos Apex APK
    max_build_duration: 60
    instance_type: mac_mini_m2
    scripts:
      # Pre-build: Clean and make gradlew executable (fixes 127 errors)
      - name: Pre-build Setup
        script: |
          chmod +x gradlew
          ./gradlew clean
      # Build the debug APK
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # Your email here
